Make it better
IYP-Programer-Yeah/PGen pull request #2
Opened 2019-09-14 18:23 UTC by Borjianamin98

2019-09-14 19:11 UTC, IYP-Programer-Yeah approved these changes

2019-09-14 19:15 UTC, IYP-Programer-Yeah requested changes
The last commit is too large to review, please break the changes into multiple merge requests. Thanks for the contribution.

2019-09-19 05:27 UTC, Borjianamin98 commented
> 
> 
> The last commit is too large to review, please break the changes into multiple merge requests. Thanks for the contribution.

Most of changes because of move files to correct place for maven structure. I don't think it is possible make it smaller.

2019-09-19 05:40 UTC, Borjianamin98 commented
> 
> 
> > The last commit is too large to review, please break the changes into multiple merge requests. Thanks for the contribution.
> 
> Most of changes because of move files to correct place for maven structure. I don't think it is possible make it smaller.



> 
> 
> The last commit is too large to review, please break the changes into multiple merge requests. Thanks for the contribution.

If you want, I can make a change, which is only fix maven structure and nothing else. after merging that, I do other refactoring and use pull request again.

2019-09-19 05:45 UTC, closed without merging